/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/html5-validation': RouteRecordInfo<'/html5-validation', '/html5-validation', Record<never, never>, Record<never, never>>,
    '/invisible-form-elements': RouteRecordInfo<'/invisible-form-elements', '/invisible-form-elements', Record<never, never>, Record<never, never>>,
    '/nested-validation': RouteRecordInfo<'/nested-validation', '/nested-validation', Record<never, never>, Record<never, never>>,
    '/simple-form': RouteRecordInfo<'/simple-form', '/simple-form', Record<never, never>, Record<never, never>>,
    '/valibot-nested-validation': RouteRecordInfo<'/valibot-nested-validation', '/valibot-nested-validation', Record<never, never>, Record<never, never>>,
    '/valibot-password-validation': RouteRecordInfo<'/valibot-password-validation', '/valibot-password-validation', Record<never, never>, Record<never, never>>,
    '/valibot-simple-form': RouteRecordInfo<'/valibot-simple-form', '/valibot-simple-form', Record<never, never>, Record<never, never>>,
  }
}
